# Generated by Django 4.2.15 on 2024-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(max_length=20, unique=True)),
                ('oil', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('brine', models.IntegerField()),
            ],
        ),
    ]
